export const FETCH_SHIPS_REQUEST = "FETCH_SHIPS_REQUEST";
export const FETCH_SHIPS_SUCCESS = "FETCH_SHIPS_SUCCESS";
export const FETCH_SHIPS_FAILURE = "FETCH_SHIPS_FAILURE";

export const FETCH_LAUNCHES_REQUEST = "FETCH_LAUNCHES_REQUEST";
export const FETCH_LAUNCHES_SUCCESS = "FETCH_LAUNCHES_SUCCESS";
export const FETCH_LAUNCHES_FAILURE = "FETCH_LAUNCHES_FAILURE";
